function exportlines(fn, outdir)

## Usage: export(fn, outdir)
##
## Exports MARSIS to JSON files containing one line each.
##
## Export a lot of files like this:
##
##  >> cellfun(@(x) @export(x, "outputdir"), glob("/path/to/files/000*"))
##

if (nargin() == 1)
  outdir = '.'
endif

[ ORBIT_NUMBER, ...
           OST_LINE_NUMBER, ...
           FRAME_ID, ...
           SCET_FRAME_WHOLE, ...
           SCET_FRAME_FRAC, ...
           CENTRAL_FREQUENCY, ...
           MARS_SOLAR_LONGITUDE, ...
           SPACECRAFT_ALTITUDE, ...
           SUB_SC_LONGITUDE, ...
           SUB_SC_LATITUDE, ...
           LOCAL_TRUE_SOLAR_TIME, ...
           SOLAR_ZENITH_ANGLE, ...
           FOOTPRINT_CENTER_LONGITUDE, ...
           FOOTPRINT_CENTER_LATITUDE, ...
           FOOTPRINT_VERTEX_LONGITUDE, ...
           FOOTPRINT_VERTEX_LATITUDE, ...
           ROUGHNESS_WITHIN_FOOTPRINT, ...
           INCIDENCE_ANGLE, ...
           FRESNEL_RADIUS, ...
           ECHO_MODULUS_MINUS1_F1_NO_IONO, ...
           ECHO_MODULUS_ZERO_F1_NO_IONO, ...
           ECHO_MODULUS_PLUS1_F1_NO_IONO, ...
           ECHO_MODULUS_MINUS1_F2_NO_IONO, ...
           ECHO_MODULUS_ZERO_F2_NO_IONO, ...
           ECHO_MODULUS_PLUS1_F2_NO_IONO, ...
           ECHO_MODULUS_MINUS1_F1_IONO, ...
           ECHO_MODULUS_ZERO_F1_IONO, ...
           ECHO_MODULUS_PLUS1_F1_IONO, ...
           ECHO_MODULUS_MINUS1_F2_IONO, ...
           ECHO_MODULUS_ZERO_F2_IONO, ...
           ECHO_MODULUS_PLUS1_F2_IONO, ...
           ECHO_MODULUS_MINUS1_F1_SIM, ...
           ECHO_MODULUS_ZERO_F1_SIM, ...
           ECHO_MODULUS_PLUS1_F1_SIM, ...
           ECHO_MODULUS_MINUS1_F2_SIM, ...
           ECHO_MODULUS_ZERO_F2_SIM, ...
           ECHO_MODULUS_PLUS1_F2_SIM ] = readmarsiscdr(fn);

for i = 1:size(FRAME_ID, 2)
  for lineIndex = 1:size(OST_LINE_NUMBER)
    outfilename = fullfile(outdir, sprintf("%08d,%08d", ...
        ORBIT_NUMBER(lineIndex), OST_LINE_NUMBER(lineIndex)));
    f = fopen(outfilename, 'w');
    fprintf(f, '{ "latitude": %g, "longitude": %g, "alt": %g, "orbit": %d, "line": %d, "frames": [', ...
        SUB_SC_LATITUDE(i), SUB_SC_LONGITUDE(i), SPACECRAFT_ALTITUDE(i),...
        ORBIT_NUMBER(i), OST_LINE_NUMBER(i));
    for frameIndex = size(FRAME_ID)
      if (frameIndex > 1)
        fputs(f, ", ");
      endif
      fprintf(f, '{"frame": %d, "iono": [', FRAME_ID(frameIndex))
      iono = ECHO_MODULUS_ZERO_F1_IONO(:,frameIndex);
      for j = 1:size(iono)
        if (j == 1)
          fprintf(f, "%g", iono(j));
        else
          fprintf(f, ", %g", iono(j));
        endif
      endfor
      fprintf(f, '],\n"sim":[');
      sim = ECHO_MODULUS_MINUS1_F1_SIM(:,frameIndex);
      for j = 1:size(sim)
        if (j == 1)
          fprintf(f, "%g", sim(j));
        else
          fprintf(f, ", %g", sim(j));
        endif
      endfor
      fprintf(f, ']} ');
    endfor
    fprintf(f, "]\n}");
    fclose(f);
  endfor
endfor

endfunction
